### ISSUE TITLE
Aggregation pipeline

### ISSUE THREAD

**Issue by dryajov** [artifacthealth/hydrate-mongodb#10]
I'm trying to figure out how to use mongodb's aggregation pipeline with `hydrate-mongodb`, any pointers on how to do that with this framework?

BTW: kudos for making this, I've been using at work and so far it has been pretty neat!

**Comment by meirgottlieb** [comment]
Thanks! For aggregation you should just access the collection directly on the session factory: 

```
this.session.factory.connection.collection("something").aggregate(...)
```

**Comment by dryajov** [comment]
Thanks!
