### ISSUE TITLE
Can't query by a field and the field not displayed in a list

### ISSUE THREAD

**Issue by nextsoftpl** [artifacthealth/hydrate-mongodb#12]
First of all, thank you for this framework, however I have a model

`import {Collection, Entity, Field} from "hydrate-mongodb";
@Entity()
@Collection("approvals")
export class Approval {

    @Field()
    approvalID: string;

    @Field()
    typeOfApproval: string;

    @Field()
    sourceSystemName: string;

    @Field()
    state: string;

}`

the field is approvalID, doing 
`em.query(Approval)
            .findAll({ state: "accepted" })
            .asPromise()`

returns the collection but without the field:

`[{"typeOfApproval":"licenses","sourceSystemName":"systemname","state":"accepted","_id":"58ca87b550de01e8ab6d4a45","id":"58ca87b550de01e8ab6d4a45"}]`

also querying against {approvalID:"5"} returns null ... works fine when querying in the mongo command line. What can be the reason? The field is String type.

Thank you in advance for the answer.

**Comment by meirgottlieb** [comment]
I tried your model and it worked fine for me. Any chance you can provide an example project?

**Comment by nextsoftpl** [comment]
@meirgottlieb thank you very much for your fast response and I was not working on the topic for a while but it came back ... unfortunatelly the thing is still not working for me. This is the only field I can not retrieve from DB, this is too weird.

**Comment by nextsoftpl** [comment]
Ooo I got it working! had to provide the name of the field in the annotation and now it works!!!
`
@Field('approvalID')
approvalID: string;
`

**Comment by meirgottlieb** [comment]
Glad you got it working. Yes, it would convert the field name to `approvalId` by default. You can change the naming strategy in the Configuration. If you set the `fieldNamingStrategy` to `NamingStrategies.None` it'll just pass through the property name.
