### ISSUE TITLE
Is pagination possible with Hydrate?

### ISSUE THREAD

**Issue by fishclaws** [artifacthealth/hydrate-mongodb#17]
I'd like to do something similar to skip(x).limit(y) but I can't find anything in the documentation? Does this ORM expose this functionality?

**Comment by meirgottlieb** [comment]
Yes, those methods are exposed on the query. For example:

```
session.query(User).find({ name: "Bob" }).skip(30).limit(15, (err, results) => { ... });
```

You can read more able it [here](https://artifacthealth.github.io/hydrate-mongodb/interfaces/findquery.html).
