### ISSUE TITLE
findOneAndUpsert should have option to return new object if created

### ISSUE THREAD

**Issue by nextsoftpl** [artifacthealth/hydrate-mongodb#22]
would be nice if findOneAndUpsert would return new object if created, just like in mongoose while setting 3rd parameter to {new: true}

**Comment by meirgottlieb** [comment]
It does. Chain with 'returnUpdated'. See docs here https://artifacthealth.github.io/hydrate-mongodb/interfaces/findoneandupdatequery.html

**Comment by nextsoftpl** [comment]
Thank you, @meirgottlieb :) working great!
