### ISSUE TITLE
Question: How do you get the collection name?

### ISSUE THREAD

**Issue by robgrimball** [artifacthealth/hydrate-mongodb#24]
I have decorated several classes with various collection names or let them use the default naming strategy.  I would like to know if there is a way via Hydrate that I can get the collection name for a given class decorated with the @Entity decoration and optionally the @Collection decoration?

**Comment by meirgottlieb** [comment]
What are you trying to do with the collection name?

**Comment by robgrimball** [comment]
Well, because I am following some of the recommendations for improved performance when getting large amounts of data, I have code that looks similar to this : 

```
const cursor = this.createSession().factory.
                                connection.collection('someCamelCaseCollectionName').find();
```

The function to which this call belongs does in fact get the class passed to it for various other reasons, and I could continue to just use hard coded values for the collection name, or I could put the hard coded value into the class itself as an additional non-persisted property, but then of course, if the naming convention is changed, or if someone adds a @Collection() decorator to it, I have to remember to change that hard coded value as well, which makes this process more fragile.  So I would like to have a way to get the collection name that Hydrate is using for the given class so that no matter what the naming strategy is and no matter if someone used a @Collection() decorator, I am getting the correct collection.

**Comment by meirgottlieb** [comment]
OK. There is a method on the [SessionFactory](https://artifacthealth.github.io/hydrate-mongodb/interfaces/sessionfactory.html) called [getCollection](https://artifacthealth.github.io/hydrate-mongodb/interfaces/sessionfactory.html#getcollection) to get the underlying MongoDB collection for an entity. For example, if you have an entity class `User` you can do the following:

```
session.factory.getCollection(User).aggregate(...);
```
