### ISSUE TITLE
Question: How to create an expireAfterSeconds index?

### ISSUE THREAD

**Issue by robgrimball** [artifacthealth/hydrate-mongodb#25]
Mongo has the ability to expires documents in the collection by creating an index with the expireAfterSeconds option.  I was wondering how this would be done with Hydrate?  

Example of how it is done in mongo : 

```
db.log_events.createIndex( { "createdAt": 1 }, { expireAfterSeconds: 3600 } )
```

It would be nice if we could do something like(haven't tried since docs don't mention options for indexes), such that when createIndexes was called it would use the options passed : 
```
@Field()
@Index({expireAfterSeconds: 3600})
log_events: Date;
```

**Comment by meirgottlieb** [comment]
Yes. The `@Index` decorator accepts an `options` property that gets passed through to the MongoDB driver.

```
@Entity()
@Index({ keys: [["created", -1]], options: { expireAfterSeconds: 3600} }) 
export class Message {
    ...
}
```
