### ISSUE TITLE
Question about sessions

### ISSUE THREAD

**Issue by robgrimball** [artifacthealth/hydrate-mongodb#27]
How important is it in Hydrate to close sessions or keep opening them to a minimum?  I realize of course that if you want to save the changes you make you need to close or flush the session, but in some places in my code I am simply opening a session in order to query and then leave it hanging with garbage collection left to get rid of the unused reference later.

Is it recommended to always close a session even if nothing is being persisted to it?  Or to keep the number of sessions opened to a minimum?  I am concerned about memory leak potential and resource usage that I am unaware of.

**Comment by meirgottlieb** [comment]
It's most likely fine. Calling `close` flushes any changes and then does some housekeeping. Mostly clearing various maps and lists it uses to track entities in the session. When I used to support `Observable` change tracking it would also stop observing the entities. In that case it would be important to call `close`, but I stopped supporting `Observable` change tracking when they removed `Object.observe` from V8. 

You should keep an eye on it to make sure it's not having an affect on garbage collection, but unless I add some sort of new change tracking in the future that is actively watching the entities, you are probably good.

**Comment by robgrimball** [comment]
Thanks for the clarification!  Closing this.
