### ISSUE TITLE
ES6 and Reactive Pattern

### ISSUE THREAD

**Issue by LazeKer** [artifacthealth/hydrate-mongodb#4]
Hi,

I'm actually working on a Angular 2 / NodeJs / MongoDB prototype and am looking for a good ODM. As an old Doctrine / Symphony developer, I made a really cool prototype with your library for the server side. 

Firstly, I want to congratulate you for making this sibling library simplifying my work.

Secondly, I would like to suggest you some improvements. For example, it could be more efficient to change callback pattern to ES6's Promises for your different async functions. It can be done with [Core-js](https://github.com/zloirock/core-js) library (for ES5 compatibility).

Examples :
1. `session.find(Player, id).catch((err) => { ... }).then((player) => { ... });`
2. `Promise.all(session.find(Player, playerId), session.find(Task, taskId)).then((objects) => { ... });`

Thirdly (and lastly), you could also consider using reactive pattern with a library such as
[RxJs](https://github.com/Reactive-Extensions/RxJS) making sessions (entityManager) or the logger Observable for events binding. 

Thanks and keep up the good work 👍 

P.S. I'll probably share / publish my prototype on my github.

**Comment by meirgottlieb** [comment]
Glad you found the library useful!

1. Personally, I prefer callbacks over promises, but I've considered making promises available on the Session. One issue is that many functions on the Session can be chained. For example, you can write:
```
session.find(Player, id).fetch("task", (err, player) => {
    ...
    player.task.doSomething();
    ...
});
```
How do you see that working if session.find returns promise? Perhaps it can be something like this:
```
session.find(Player, id).fetch("task").asPromise().then(...)
```
I don't use promises much anymore so some feedback on the API would be helpful.

2. I have not considered using Observables for the logger or session. Can you give an example of how you would use the session and logger if they were observable? However, I have considered making query results available through an Observable. For example:
```
session.query(Player).findAll({ ... }).asObservable().takeUntil(...)
```
Thoughts?

**Comment by LazeKer** [comment]
It could absolutely look like that.

For the Promise cases and as an example, I'm wrapping a query in a promise like this:
```typescript
getPlayerByName(playerName:string): Promise<Player> {
    // Create and return a promise of player.
    return new Promise<Player>((resolve, reject) => {
        // Trying to find the player document.
        this.session.query(Player).findOne({name:playerName}, (error, player) => {
            if (error) { // If an error occured, we reject the promise.
                reject(error);
            } else { 
                resolve(player);
            }
        });
    });
}
```

In `queryBuilder.ts`, you could consider implementing something like:

```typescript
asPromise(): Promise<Object> {
    // Create and return the promise.
    return new Promise((resolve, reject) => {
        // Wrapping of the classic callback handler.
        this.handleCallback((error, result) => {
            if (error !== null) {
                reject(error);
            }
            else {
                resolve(result);
            }
        });
    });
}
```

Making query results observable is a great idea too. Like Promise, it could be very useful.

For Session the Observable pattern is more efficient than EventListener (allowing you to merge, map, filter, ... all events going through the observable pipe). I don't have good examples because Session eventEmitter is actually just for error events and it can easily be wrapped in an observable object. But if you're interested in this topic, here are a few useful links:

Readable documentation (not ths JS implementation of the library):
http://reactivex.io/documentation/observable.html
http://reactivex.io/documentation/subject.html
...

Some useful examples:
https://github.com/Reactive-Extensions/RxJS/blob/master/examples/autocomplete/autocomplete.js

**Comment by meirgottlieb** [comment]
Most recent release, 0.12.0, adds asPromise() for queries, find, etc.

**Comment by meirgottlieb** [comment]
Added support for Observable in release 0.13.1. Please give it a try and let me know how it works for you. Thanks!
