### ISSUE TITLE
"Object type is not mapped as an entity."

### ISSUE THREAD

**Issue by StephanyBatista** [artifacthealth/hydrate-mongodb#6]
Hello,

I'm facing this error. In the session factory, _mappingRegistry, I see my class, but when I make:

`await session.query(User).findOne({email: req.body.email}).asPromise()`

I have this error. 

Below a example of my code:

`
import * as model from "../model/user";
var config = new Configuration();
config.addMapping(new AnnotationMappingProvider(model.User));

        MongoClient.connect('mongodb://localhost/mydatabase', (err, db) => {
            if(err) throw err;
            
            config.createSessionFactory(db, (err, sessionFactory) => {        
                 
                 Injector.register("sessionFactory", sessionFactory);
            });
        });`

and 

`import {User} from '../../model/User';

var sessionFactory = <SessionFactory>Injector.getRegistered("sessionFactory");
var session = sessionFactory.createSession();        
var userSaved = await session.query(User).findOne({email: req.body.email}).asPromise();
`

**Comment by meirgottlieb** [comment]
Can you please post the code for your User class?

**Comment by StephanyBatista** [comment]
Yes, 

import {DomainException} from './domain.exception';
import {Entity, Field} from "hydrate-mongodb";

@Entity()
export class User{
    
    @Field()
    id: string;
    @Field()
    name: string;
    @Field()
    email: string;
    @Field()
    birthday: Date;
    @Field()
    private _password: string;

    get password() {
        return this._password;
    }
    
    constructor(id: string, name: string, email: string, birthday: Date){
        
        DomainException.when(name == null || name == '', "Name is required");
        DomainException.when(email == null || email == '', "E-mail is required");
        DomainException.when(birthday == null, "Birthday is required");
        
        if(id)
            this.id = id;
        this.name = name;
        this.email = email;
        this.birthday = birthday;
    }

    updatePassword(password: string){
        this._password = password;
    }

    hasId(){
        return this.id != null && this.id != '';
    }
}

**Comment by meirgottlieb** [comment]
That looks fine. Did you enable the `emitDecoratorMetadata` and `experimentalDecorators` TypeScript compiler options?

**Comment by meirgottlieb** [comment]
Just an FYI, you cannot map `id` as a field and cannot assign a value to it. That will be automatically assigned with the string version of the ObjectID.

**Comment by StephanyBatista** [comment]
![image](https://cloud.githubusercontent.com/assets/6475229/21529846/2e58fbca-cd1b-11e6-8885-206cdb1984a7.png)

{
    "compilerOptions": {

        "module": "commonjs",
        "target": "ES6",
        "noImplicitAny": false,
        "sourceMap": true,
        "experimentalDecorators": true,
        "lib": ["es6", "dom"],
        "emitDecoratorMetadata": true
    },
    "exclude": [
        "node_modules"
    ]
}

I don't understand why this is not work :)

**Comment by meirgottlieb** [comment]
Any chance you can put together an example project and attach as a zip file?

**Comment by meirgottlieb** [comment]
Here is an [example project](https://github.com/artifacthealth/hydrate-mongodb-examples). Please let me know if that helps.

**Comment by StephanyBatista** [comment]
Thanks, I saw your example code. What I saw in my code is that if I make the query in the code that I open the mongodb it works, but if I get the SessionFactory stored in a injection I have that error.

Below my code that I open the mongodb 

import {MongoClient} from "mongodb";
import {Configuration, AnnotationMappingProvider, Session, SessionFactory} from "hydrate-mongodb";
import {User} from "../model/user";
import Injector from '../cross/injector';

export class ConfigSessionFactory{

    public static create(){

        var config = new Configuration();
        config.addMapping(new AnnotationMappingProvider(User));
        
        MongoClient.connect('mongodb://localhost/mydatabase', (err, db) => {
            if(err) throw err;
            
            config.createSessionFactory(db, (err, sessionFactory: SessionFactory) => {

                Injector.register("sessionFactory", sessionFactory);
                
                //Code works
                // var session = sessionFactory.createSession();
                // session.query(User).findOne({email: "req.body.email"}, (err, user: User) => {
                //     var a = user;
                //     var b = 1;
                // });

            });
        });
    }
}

**Comment by meirgottlieb** [comment]
One comment is you should be checking for an error in the callback for createSessionFactory but that's probably not the issue. Any chance you can share the repo so I can debug it?

**Comment by StephanyBatista** [comment]
Of course. https://github.com/StephanyBatista/newHome

My code is bad because I'm studying how put hydrate-mongodb. But see the bootstrap.ts and user.controller.ts files. 

I saw that the problem is in MappingRegistry.prototype.getMappingForConstructor file, beucase it doesn't get the entity in mappings, prototype in mappings and the parameter are differents.

**Comment by StephanyBatista** [comment]
Has some change of key of mappings be the user name class? In ORM I understand that a class cannot have the same name in table.

**Comment by meirgottlieb** [comment]
I spent some time working with the repository and cleaned up a few things. All your tests are passing now. I created a [pull requested](https://github.com/StephanyBatista/newHome/pull/1). Let me know if you have any questions. In process I did find and fix a bug in Hydrate so thanks for sharing!

**Comment by StephanyBatista** [comment]
Ok, I thanks you by your time! Your project is very nice! If you need of help I can contribute, but I'm studying nodejs :)

**Comment by meirgottlieb** [comment]
Glad you like it! Let me know if you have any other questions.

**Comment by StephanyBatista** [comment]
No, Thanks!
