### ISSUE TITLE
How use $in with entity field.

### ISSUE THREAD

**Issue by StephanyBatista** [artifacthealth/hydrate-mongodb#8]
Hello!

I'm trying to use $in with entity field. I have this class and I would like to find by a array of id.

@Entity()
class Test{
    @Field('style')
    @Fetch(FetchType.Eager)
    private _style: Style;
}

But when I try to use I find below I have a error "Bad value":
filter['_style'] = { '_id': { '$in': [ObjectId("58aa2d42a288f20fc812a1a5"), ObjectId("58aa2d42a288f20fc812a1a5")] } };

I studied the code and I saw the class EntityMapping.js and in the method write has the validation below:
if (!this.inheritanceRoot.identity.validate(id))...

**Comment by meirgottlieb** [comment]
Hey @StephanyBatista,

Try this:

```
session.query(Test).findAll({ style: { $in: [ 
    session.getReference(Style, "58aa2d42a288f20fc812a1a5"),
    session.getReference(Style, "58aa2d42a288f20fc812a1a5") 
] }}, (err, result) => {
        ...
});
```
The $in statement is expecting a list of Styles. Hydrate will convert it to id's for you. The call to getReference creates a placeholder if you don't have the entity. For you already have the entity, you can use that instead. For example:
```
session.query(Style).findAll((err, styles) => {
    if (err) throw err;

    session.query(Test).findAll({ style: { $in: styles }}, (err, results) => {
        ...
    });
});
```

Did that help?

**Comment by StephanyBatista** [comment]
Ohhh Nice! 

Here it's working! Thanks! I think that now this issues will to help others dev.

Thanks!

**Comment by meirgottlieb** [comment]
Sure thing. It's helpful to me as well to see where people are getting hung up. I'll add some better error messages.
